### ISSUE TITLE
This Event Edit page is not loading

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/admin-client#225]
https://avannotate.netlify.app/en/projects/tanyaclement+harvard-1953/events/30f86c81-cb93-436a-9b14-8599257f4308/edit

Harvard -- August 5, Afternoon Edit Settings

From Sara:

The page that isn't loading throws this error: 

index.BxQph4Bk.js:24 TypeError: Cannot read properties of undefined (reading 'label')
    at Object.property (EventForm.D10N7HDF.js:1:3742)
    at f (Table.DSCtwTZG.js:1:391)
    at Table.DSCtwTZG.js:1:2383
    at Array.map (<anonymous>)
    at Table.DSCtwTZG.js:1:2280
    at Array.map (<anonymous>)
    at J (Table.DSCtwTZG.js:1:2212)
    at eu (index.BxQph4Bk.js:22:16958)
    at ga (index.BxQph4Bk.js:24:43681)
    at va (index.BxQph4Bk.js:24:39486)
diﾠ@ﾠindex.BxQph4Bk.js:24

**Comment by ajolipa** [comment]
This should now be fixed! (Issue was an annotation set that was attached to a file that was no longer in this event.... not sure how it got into that state, but deleting that annotation set fixed it I believe. At least I am not getting any error currently.)
